### ISSUE TITLE
Erreur de calcul bonus d'attaque avec modificateur général

### ISSUE THREAD

**Issue by jibri** [SvenWerlen/pathfinderfr-android#22]
En tant qu'alchimiste de N3 j'utilise une fronde.
Mon bonus d'attaque avec cet objet est de 3+3=6, mais j'ai également le don "Tir à bout pourtant" qui permet d'ajouter 1 à tout mes jets d'attaque et de dégat à distance.

Dans l'application, j'ai ajouté cette modification avec comme caractéristique : 
 - Bonus d'attaque à distance +1
 - Bonus de dégât à distance +1

Cependant, cette valeur s'affiche dans le détail des calcul d'attaque, mais n'est pas prise en compte dans le résultat.
![83772177_545537262713388_6600661518956625920_n](https://user-images.githubusercontent.com/6851601/73608471-a3f67a00-45c3-11ea-8dd8-675ae1ae0ce4.png)

**Comment by SvenWerlen** [comment]
Merci. J'ai été capable de reproduire le problème grâce à la capture. Je regarde ce qui ne fonctionne pas.

**Comment by SvenWerlen** [comment]
Il faut activer le bonus sur ton arme pour qu'il soit pris en compte. 

![image](https://user-images.githubusercontent.com/938060/73611438-e2823980-45af-11ea-8090-edbfc2c37e8e.png)

Par contre, il y a néanmoins un bogue sur l'écran de détail qui ne devrait pas afficher le bonus de +1 lorsque ce dernier n'est pas activé.

**Comment by SvenWerlen** [comment]
Le bogue d'affichage a été corrigé dans la version 3.9.1 (à venir).
