### ISSUE TITLE
Possibilité d'ajout d'objets au référentiel

### ISSUE THREAD

**Issue by jibri** [SvenWerlen/pathfinderfr-android#23]
Est-il possible d'ajouter manuellement des objets au référentiel, en plus de ceux récupérés depuis Pathfinder-FR ?
Par exemple, en tant qu'alchimiste j'utilise evidemment des bombes. Malheureusement je ne peux pas affiche ces bombes commes des armes dans le détail du personnage. Et je n'ai donc pas accès de facon rapide au info d'attaque et de dégats de mes bombes. Et c'est encore plus genant lorsque l'on utilise des bonus tels que "Tir à bout portant" ou "Lancer improvisé".
Autre exemple, j'utilise une lance courte au CàC, mais cette arme n'est pas référencée dans Pathfinder-FR.

**Comment by SvenWerlen** [comment]
Les données viennent de fichiers au format YML (voir [pathfinderfr-data](https://github.com/SvenWerlen/pathfinderfr-data/tree/Feature/3.6/data)). En ce moment, seules les données officielles sont importées mais il serait possible d'ajouter d'autres facilement. Je te propose de venir en parler sur Discord: https://discord.gg/Dhg3HW9

**Comment by SvenWerlen** [comment]
Je fais du ménage dans mes projets et ne prévois plus faire de développement sur cette application.
Merci pour votre compréhension
