### ISSUE TITLE
Bestiary in the DM section?

### ISSUE THREAD

**Issue by velpaxl** [SvenWerlen/pathfinderfr-android#24]
Bonjour,
Félicitations pour le boulot abattu !
Je me demandais s’il y avait une raison pour ne pas avoir inclus le Bestiaire du Wiki dans la section du MJ ?
Je serai ravi de filer un coup de main, je dev principalement sur des technos Web, mais j’ai une bonne pratique de python aussi !

P. S. : je ne savais pas trop comment faire remonter cette question, donc je me suis servi des _issues_, même si ce n’est pas forcément le meilleur endroit.

**Comment by SvenWerlen** [comment]
Merci!
Je prévoyais intégrer le bestiaire mais les données sont difficiles à extraire. C'est la raison pour laquelle ces capacités ne sont pas encore disponibles dans l'application. Je pourrais simplement intégrer la page HTML telle quelle mais ça donnerait pas très bien.

Le meilleur moyen de discuter avec la mini communauté autour de l'application, c'est de nous rejoindre sur Discord: https://discord.gg/Dhg3HW9

Toute aide est la bienvenue! Côté python, il y a les scripts d'extraction des données (mais mes scripts ne sont pas terribles ;-)). Sinon, le simple fait de tester l'application avant les publications officielles m'aide beaucoup aussi.
