### ISSUE TITLE
Ajout des dons d'école dans le catalogue de dons. 

### ISSUE THREAD

**Issue by wagnerax** [SvenWerlen/pathfinderfr-android#25]
Les dons d'écoles sont listés à part dans le site Web.
https://www.pathfinder-fr.org/Wiki/Pathfinder-RPG.dons%20d%c3%a9cole.ashx

Néanmoins, ce serait pratique de pouvoir les intégrer dans le catalogue de dons.

**Comment by SvenWerlen** [comment]
Les dons d'école semblent être déjà pris en charge par l'application. Pourrais-tu m'indiquer quel don n'est pas présent dans le catalogue pour que j'investigue.

**Comment by wagnerax** [comment]
Salut !

Ils sont bien listés dans la catégorie dons ? Techniquement, j'en trouve
aucun, entre autre, je cherche 'kirin' pour 'école du kirin' par exemple
mais aucun match pour la fonction filtre et pas d'entrée qui commence par
'école' qui corresponde.

Le lun. 12 oct. 2020 à 15:35, Sven Werlen <notifications@github.com> a
écrit :

**Comment by SvenWerlen** [comment]
Oui, j'ai bien 3 dons en recherchant "kirin".

![image](https://user-images.githubusercontent.com/938060/95811752-f0ad5b80-0ce1-11eb-9a50-b01fc9c169b1.png)

Il est possible que les données soient plus à jour dans la version 4.x (beta) sur laquelle je travaille. Tu peux devenir testeur bêta à l'adresse suivante: https://play.google.com/store/apps/details?id=org.pathfinderfr

_Attention, je recommande fortement de conserver une copie PDF ou un export des PJs au cas où. La version 4.x modifie beaucoup la manière de gérer les versions des données et ça pourrait corrompre certains personnages._

**Comment by wagnerax** [comment]
Ça marche, je vais beta tester.
Sur la version actuelle, pas de dons d'école, cf Screenshot.


Le mar. 13 oct. 2020 à 05:28, Sven Werlen <notifications@github.com> a
écrit :

**Comment by SvenWerlen** [comment]
Je fais du ménage dans mes projets et ne prévois plus faire de développement sur cette application.
Merci pour votre compréhension
